SELECT DISTINCT YEAR , LEVEL , PARENTTOPIC AS "TOPIC", COUNT(TOPICNAME) AS "NUMBER OF ARTICLES",
        MIN(LEN(SUMMARY))  AS "MIN_SUMMARY", MAX(LEN(SUMMARY)) AS "MAX_SUMMARY", 
        MIN(LEN(LEARNINGOUTCOME)) AS "MIN_LEARNING_OUTCOME", MAX(LEN(LEARNINGOUTCOME)) AS "MAX_LEARNING_OUTCOME"

FROM {{ source('my_new_project', 'urldata') }}
WHERE YEAR IS NOT NULl AND LEVEL IS NOT NULL AND NOT (SUMMARY = 'Summary section is missing.') AND NOT (LEARNINGOUTCOME = 'Learning Outcomes section is missing.')
GROUP BY YEAR, LEVEL, PARENTTOPIC
ORDER BY YEAR


