version: 2

models:
  - name: my_model
    description: Model representing final data
    columns:
      - name: YEAR
        description: year of cfa article
        tests:
          - not_null
      - name: LEVEL
        description: level of cfa article
        tests:
          - not_null